// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwCallMedia } from '@signalwire/web-components/sw-call-media';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-call-media>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const CallMedia = createSwComponent({
  tagName: 'sw-call-media',
  elementClass: SwCallMedia,
  events: {}
});

export type { SwCallMedia };
