// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwCallWidget } from '@signalwire/web-components/sw-call-widget';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-call-widget>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const CallWidget = createSwComponent({
  tagName: 'sw-call-widget',
  elementClass: SwCallWidget,
  events: {
    onCallEnded: 'sw-call-ended',
    onCallHangup: 'sw-call-hangup',
    onContentDrawerClose: 'sw-content-drawer-close',
    onDial: 'sw-dial',
    onDisplayContent: 'sw-display-content',
    onFullscreenToggle: 'sw-fullscreen-toggle',
    onModalClose: 'sw-modal-close',
    onTranscriptToggle: 'sw-transcript-toggle'
  }
});

export type { SwCallWidget };
