// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwClickToCall } from '@signalwire/web-components/sw-click-to-call';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-click-to-call>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const ClickToCall = createSwComponent({
  tagName: 'sw-click-to-call',
  elementClass: SwClickToCall,
  events: {}
});

export type { SwClickToCall };
