// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwDeviceSelector } from '@signalwire/web-components/sw-device-selector';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-device-selector>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const DeviceSelector = createSwComponent({
  tagName: 'sw-device-selector',
  elementClass: SwDeviceSelector,
  events: {
    onDeviceChange: 'sw-device-change'
  }
});

export type { SwDeviceSelector };
