// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwLocalCamera } from '@signalwire/web-components/sw-local-camera';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-local-camera>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const LocalCamera = createSwComponent({
  tagName: 'sw-local-camera',
  elementClass: SwLocalCamera,
  events: {}
});

export type { SwLocalCamera };
