// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwParticipantControls } from '@signalwire/web-components/sw-participant-controls';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-participant-controls>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const ParticipantControls = createSwComponent({
  tagName: 'sw-participant-controls',
  elementClass: SwParticipantControls,
  events: {
    onParticipantPinToggle: 'sw-participant-pin-toggle',
    onParticipantVolumeChange: 'sw-participant-volume-change'
  }
});

export type { SwParticipantControls };
