// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { SwParticipants } from '@signalwire/web-components/sw-participants';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for `<sw-participants>`.
 *
 * Props map to element properties (not attributes), so object props such as
 * `call` pass through correctly. Events surface as `on*` props.
 */
export const Participants = createSwComponent({
  tagName: 'sw-participants',
  elementClass: SwParticipants,
  events: {
    onParticipantMuteAudio: 'sw-participant-mute-audio',
    onParticipantMuteVideo: 'sw-participant-mute-video',
    onParticipantRemove: 'sw-participant-remove'
  }
});

export type { SwParticipants };
