// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run `npm run generate`.

// Importing this barrel registers every element. Prefer the per-component
// subpath (`@signalwire/react-ui/call-controls`) so bundlers only pull what
// you use — custom-element registration is a side effect and cannot be
// tree-shaken away.
export { CallMedia } from './components/CallMedia';
export { SelfMedia } from './components/SelfMedia';
export { LocalCamera } from './components/LocalCamera';
export { CallStatus } from './components/CallStatus';
export { CallProvider } from './components/CallProvider';
export { CallDialpad } from './components/CallDialpad';
export { AudioLevel } from './components/AudioLevel';
export { ClickToCall } from './components/ClickToCall';
export { CallControls } from './components/CallControls';
export { Participants } from './components/Participants';
export { ParticipantControls } from './components/ParticipantControls';
export { Directory } from './components/Directory';
export { DeviceSelector } from './components/DeviceSelector';
export { CallWidget } from './components/CallWidget';
