/**
 * The Objective-C source injected for VoIP push.
 *
 * Why a separate category file rather than editing `AppDelegate.swift`:
 *
 * - Regex-patching a Swift `AppDelegate` fails silently when Expo changes its
 *   template, which is worse than not generating anything at all.
 * - Swift cannot `import RNCallKeep` — callkeep's podspec does not expose a
 *   consumable Swift module, and bridging headers do not work around it
 *   (react-native-callkeep#856, open since Aug 2025). Objective-C can.
 *
 * A category adds behaviour to the generated `AppDelegate` without touching
 * its source, so `expo prebuild` regenerating that file cannot break it.
 *
 * What it does: registers a `PKPushRegistry` on launch and, when a VoIP push
 * arrives, reports it straight to CallKit. This has to happen in native code —
 * on a cold start the JavaScript bundle is not running, and iOS terminates an
 * app that does not report a VoIP push to CallKit almost immediately.
 *
 * The payload MUST carry `call_id`. `CallRegistry` fuses the native entry with
 * the SDK call by that id; without it the registry falls back to "the single
 * unmatched inbound call within the fusion timeout" and breaks as soon as two
 * calls overlap.
 */
export const VOIP_PUSH_SOURCE = `//
//  SignalWireVoipPush.m
//
//  GENERATED by @signalwire/react-native's Expo config plugin.
//  Edits are overwritten on the next \`expo prebuild\`.
//
//  Registers a PushKit registry and reports incoming VoIP pushes to CallKit
//  before JavaScript is running. See docs/push-setup.md.
//

#import <Foundation/Foundation.h>
#import <objc/runtime.h>
#import <PushKit/PushKit.h>
#import <UIKit/UIKit.h>

#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

#import "RNCallKeep.h"

// Posted whenever the PushKit token changes, so JavaScript can register the
// device with your server. Payload: @{ @"token": <hex string> }.
NSString *const SignalWireVoipTokenNotification = @"SignalWireVoipTokenNotification";

@interface SignalWireVoipPushDelegate : NSObject <PKPushRegistryDelegate>
@property (nonatomic, strong) PKPushRegistry *registry;
@end

@implementation SignalWireVoipPushDelegate

+ (instancetype)shared {
  static SignalWireVoipPushDelegate *shared = nil;
  static dispatch_once_t onceToken;
  dispatch_once(&onceToken, ^{
    shared = [SignalWireVoipPushDelegate new];
  });
  return shared;
}

- (void)start {
  if (self.registry != nil) {
    return;
  }
  self.registry = [[PKPushRegistry alloc] initWithQueue:dispatch_get_main_queue()];
  self.registry.delegate = self;
  self.registry.desiredPushTypes = [NSSet setWithObject:PKPushTypeVoIP];
  // Logged because VoIP push has no other visible failure mode: a build signed
  // without the aps-environment entitlement registers fine and then silently
  // receives nothing, while APNs keeps reporting every push as delivered.
  NSLog(@"[SignalWireVoipPush] registry started, awaiting credentials");
}

+ (NSString *)cachedToken {
  return objc_getAssociatedObject(self, @selector(cachedToken));
}

+ (void)setCachedToken:(NSString *)token {
  objc_setAssociatedObject(self, @selector(cachedToken), token, OBJC_ASSOCIATION_COPY_NONATOMIC);
}

- (void)pushRegistry:(PKPushRegistry *)registry
    didUpdatePushCredentials:(PKPushCredentials *)credentials
                     forType:(PKPushType)type {
  const unsigned char *bytes = credentials.token.bytes;
  NSMutableString *hex = [NSMutableString stringWithCapacity:credentials.token.length * 2];
  for (NSUInteger i = 0; i < credentials.token.length; i++) {
    [hex appendFormat:@"%02x", bytes[i]];
  }
  // Cached because the token arrives during launch, long before React Native
  // has a bridge to deliver it over. Without this the first launch after
  // install registers no device and the first push silently goes nowhere.
  [SignalWireVoipPushDelegate setCachedToken:[hex copy]];
  NSLog(@"[SignalWireVoipPush] token %@", hex);

  [[NSNotificationCenter defaultCenter] postNotificationName:SignalWireVoipTokenNotification
                                                      object:nil
                                                    userInfo:@{ @"token": [hex copy] }];
}

/** callkeep hands this dictionary back to JS on didDisplayIncomingCall. */
- (NSDictionary *)payloadWithCallId:(NSString *)callId extras:(NSDictionary *)extras {
  NSMutableDictionary *result = [NSMutableDictionary dictionaryWithDictionary:extras];
  result[@"callId"] = callId;
  return result;
}

- (void)pushRegistry:(PKPushRegistry *)registry
    didReceiveIncomingPushWithPayload:(PKPushPayload *)payload
                              forType:(PKPushType)type
                withCompletionHandler:(void (^)(void))completion {
  NSDictionary *data = payload.dictionaryPayload;
  NSLog(@"[SignalWireVoipPush] push received, keys %@", [[data allKeys] componentsJoinedByString:@","]);

  // A UUID is required by CallKit. Prefer one the sender chose so the server
  // and the device agree; otherwise mint one here.
  NSString *uuid = data[@"uuid"] ?: [[NSUUID UUID] UUIDString];
  NSString *callId = data[@"call_id"] ?: @"";
  NSString *handle = data[@"from"] ?: @"Unknown";
  NSString *callerName = data[@"from_name"] ?: @"Unknown caller";

  // Everything the sender added beyond the known keys is forwarded verbatim.
  // A bridge topology puts a single-use token here, and JavaScript cannot ask
  // for it later: by the time the app is running, the push is gone.
  NSMutableDictionary *extras = [NSMutableDictionary dictionary];
  NSSet *known = [NSSet setWithArray:@[ @"uuid", @"call_id", @"from", @"from_name", @"aps" ]];
  for (NSString *key in data) {
    if (![known containsObject:key]) {
      id value = data[key];
      if ([value isKindOfClass:[NSString class]]) {
        extras[key] = value;
      }
    }
  }

  // Reported unconditionally, even when the payload is malformed: iOS kills an
  // app that takes a VoIP push without reporting a call, and a call that ends
  // itself as missed is far better than a terminated process.
  [RNCallKeep reportNewIncomingCall:uuid
                             handle:handle
                         handleType:@"generic"
                           hasVideo:NO
                localizedCallerName:callerName
                    supportsHolding:YES
                       supportsDTMF:YES
                   supportsGrouping:NO
                 supportsUngrouping:NO
                        fromPushKit:YES
                            payload:[self payloadWithCallId:callId extras:extras]
              withCompletionHandler:completion];
  NSLog(@"[SignalWireVoipPush] reported call %@ to CallKit", uuid);
}

@end

/**
 * Bridges the PushKit token to JavaScript.
 *
 * getToken exists alongside the event because of the ordering problem above:
 * a listener attached after the token arrived would wait forever, so JS reads
 * the cached value once at startup and subscribes for later refreshes.
 */
@interface SignalWireVoipPush : RCTEventEmitter <RCTBridgeModule>
@end

@implementation SignalWireVoipPush

RCT_EXPORT_MODULE();

+ (BOOL)requiresMainQueueSetup {
  return NO;
}

- (NSArray<NSString *> *)supportedEvents {
  return @[ @"SignalWireVoipToken" ];
}

- (void)startObserving {
  [[NSNotificationCenter defaultCenter] addObserver:self
                                           selector:@selector(onToken:)
                                               name:SignalWireVoipTokenNotification
                                             object:nil];
}

- (void)stopObserving {
  [[NSNotificationCenter defaultCenter] removeObserver:self];
}

- (void)onToken:(NSNotification *)note {
  NSString *token = note.userInfo[@"token"];
  if (token != nil) {
    [self sendEventWithName:@"SignalWireVoipToken" body:@{ @"token": token }];
  }
}

RCT_EXPORT_METHOD(getToken
                  : (RCTPromiseResolveBlock)resolve reject
                  : (RCTPromiseRejectBlock)reject) {
  resolve([SignalWireVoipPushDelegate cachedToken]);
}

@end

@implementation UIApplication (SignalWireVoipPush)

+ (void)load {
  // Starts the registry once the app has finished launching, without needing a
  // line inside the generated AppDelegate.
  [[NSNotificationCenter defaultCenter]
      addObserverForName:UIApplicationDidFinishLaunchingNotification
                  object:nil
                   queue:[NSOperationQueue mainQueue]
              usingBlock:^(NSNotification *_Nonnull note) {
                [[SignalWireVoipPushDelegate shared] start];
              }];
}

@end
`;
