import { NativeEventEmitter, NativeModules, Platform } from 'react-native';

import { logger } from '@signalwire/react';

interface VoipPushModule {
  getToken(): Promise<string | null>;
}

const TOKEN_EVENT = 'SignalWireVoipToken';

function nativeModule(): VoipPushModule | undefined {
  return (NativeModules as Record<string, VoipPushModule | undefined>).SignalWireVoipPush;
}

/**
 * Reads the current PushKit token, if one has been issued.
 *
 * Returns `null` rather than throwing when the token is not available yet, and
 * on Android, where VoIP push does not exist — callers register a device the
 * same way on both platforms and simply get nothing to send here.
 *
 * iOS issues the token during launch, before React Native has a bridge, so the
 * native side caches it. Reading it once at startup is therefore not an
 * optimisation: a listener attached after that moment would wait forever.
 */
export async function getVoipToken(): Promise<string | null> {
  if (Platform.OS !== 'ios') {
    return null;
  }

  const module = nativeModule();
  if (!module) {
    logger.debug(
      'VoIP push module missing. It is generated by the Expo config plugin with ' +
        '`enableVoipPush`; a bare React Native app must add the native source by hand.'
    );
    return null;
  }

  try {
    return (await module.getToken()) ?? null;
  } catch (error) {
    logger.warn('Failed to read the VoIP push token:', error);
    return null;
  }
}

/**
 * Subscribes to PushKit token changes.
 *
 * iOS reissues the token after reinstalls, restores and occasional system
 * events, and a stale token fails silently at APNs — the push simply never
 * arrives. Re-register whenever this fires.
 *
 * Returns an unsubscribe function; a no-op where VoIP push does not apply.
 */
export function onVoipTokenChange(listener: (token: string) => void): () => void {
  if (Platform.OS !== 'ios') {
    return () => undefined;
  }

  const module = nativeModule();
  if (!module) {
    return () => undefined;
  }

  const emitter = new NativeEventEmitter(module as never);
  const subscription = emitter.addListener(TOKEN_EVENT, (event: { token?: string }) => {
    if (event?.token) {
      listener(event.token);
    }
  });

  return () => subscription.remove();
}

/**
 * Reads the current token and watches for changes, in one call.
 *
 * The common shape: fire immediately if a token already exists, then again on
 * every refresh. Deduplicates, so a refresh matching the cached value does not
 * re-register.
 */
export function watchVoipToken(listener: (token: string) => void): () => void {
  let lastSeen: string | null = null;

  const emit = (token: string): void => {
    if (token === lastSeen) {
      return;
    }
    lastSeen = token;
    listener(token);
  };

  void getVoipToken().then((token) => {
    if (token) {
      emit(token);
    }
  });

  return onVoipTokenChange(emit);
}
