#!/usr/bin/env node
/**
 * Generates one React wrapper per SignalWire web component.
 *
 * Hand-writing fourteen near-identical files invites drift; regenerating from
 * `components.mjs` keeps the event maps and naming consistent, and makes adding
 * a component a one-line change. Run `npm run generate` after editing the
 * manifest, and commit the output so consumers never run codegen.
 */
import { readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const COMPONENTS = JSON.parse(
  readFileSync(new URL('./components.json', import.meta.url), 'utf8')
);

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const srcDir = join(root, 'src', 'components');

const BANNER = `// GENERATED by scripts/generate.mjs — do not edit.
// Edit scripts/components.json and run \`npm run generate\`.
`;

function componentSource({ tag, className, name, events }) {
  const eventEntries = Object.entries(events);
  const eventsLiteral = eventEntries.length
    ? `{\n${eventEntries.map(([prop, dom]) => `    ${prop}: '${dom}'`).join(',\n')}\n  }`
    : '{}';

  return `${BANNER}
// Lit elements register themselves with customElements on import, and touch the
// DOM at module scope — so this is a browser-only, client-side module.
'use client';

import { ${className} } from '@signalwire/web-components/${tag}';

import { createSwComponent } from '../createSwComponent';

/**
 * React wrapper for \`<${tag}>\`.
 *
 * Props map to element properties (not attributes), so object props such as
 * \`call\` pass through correctly. Events surface as \`on*\` props.
 */
export const ${name} = createSwComponent({
  tagName: '${tag}',
  elementClass: ${className},
  events: ${eventsLiteral}
});

export type { ${className} };
`;
}

await mkdir(srcDir, { recursive: true });

for (const component of COMPONENTS) {
  await writeFile(join(srcDir, `${component.name}.ts`), componentSource(component), 'utf8');
}

const barrel = `${BANNER}
// Importing this barrel registers every element. Prefer the per-component
// subpath (\`@signalwire/react-ui/call-controls\`) so bundlers only pull what
// you use — custom-element registration is a side effect and cannot be
// tree-shaken away.
${COMPONENTS.map((c) => `export { ${c.name} } from './components/${c.name}';`).join('\n')}
`;

await writeFile(join(root, 'src', 'index.ts'), barrel, 'utf8');

console.log(`Generated ${COMPONENTS.length} wrappers and the barrel.`);
